# Generated by Django 4.2.9 on 2024-02-25 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("music_discovery", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="playlist",
            name="id",
        ),
        migrations.AlterField(
            model_name="playlist",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
