# Generated by Django 4.2.9 on 2024-02-25 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music_discovery", "0002_remove_playlist_id_alter_playlist_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="playlist",
            name="user",
        ),
        migrations.AddField(
            model_name="playlist",
            name="id",
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
