# Generated by Django 4.2.9 on 2024-03-02 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music_discovery", "0004_playlist_user_alter_playlist_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="playlist",
            name="song_art_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
