# Generated by Django 4.2.9 on 2024-03-04 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music_discovery", "0007_listeninghistory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listeninghistory",
            name="album_name",
        ),
        migrations.RemoveField(
            model_name="listeninghistory",
            name="artist_name",
        ),
        migrations.RemoveField(
            model_name="listeninghistory",
            name="track_name",
        ),
        migrations.RemoveField(
            model_name="listeninghistory",
            name="uri",
        ),
        migrations.AddField(
            model_name="listeninghistory",
            name="tracks",
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="listeninghistory",
            name="played_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
